language: node_js
node_js:
- '6'
script:
- ./prepare.sh
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: jHB0IfT4ayiY01SNtSbsCAQd7O7qVOzBFW045qWIBeg4Ru+fcDEiEOe6fq1dPBQodrjfti5cKJyoJDpZ9EwPh5ZrANwj9B+IltOaJapR0wSX5vDlYVMBZuMR118JBfxxosw8SxQlVY9YNNRMKSxa75Ud4TkkWSzFOYvHhN8DdJYzBbFZW8LfubIpxenySkTtaBzhwmPqoVvjbq18Dp40FbkBFC40lfFe1UlGN+LQt3PjE7Gxg1yWzoWRL5eFbetdd+VBH4SVTiu/LvVZ8hhk2f3A72CaomiyPKQbzdt+/4skz9pEJZFdb3JvxaO8f0h5X8lS112/u+2qdT6xaAkYPvSipBdOypaLoG1aKgFuVseovsLn1/N8PqAWKzscmd1bf0USKxBkFw1yrvZFFxvmm2nZ8rUzCWrt7ISMvStO//4/YzQUzE1Lm7Z31qji9L0Uc8Xvg356NldNKLpelWJrsae8H5WIukDOdeE7twJ9RYdJ1M6+0jOzR//VMg5pTW0hNOQFDMy9IoAiqNqyUh0bKjf6MS5+/5QJsvzJip+rkuZnVMGxCMlZBT3gfZJSHRXYEIa2DR1p8g7+WBi6yUYSiF6pSjRdmnegnCcfXHpNzSYvdKFAJt5ea911iFtjYb26i4zMuKge3wj+xpSr6RJ/CyhiQudspipJF6gkE2t7sgM=
  file:
    - windows.zip
    - linux.zip
    - mac.zip
  on:
    tags: true
  overwrite: true
  skip_cleanup: true
